# NumPy

In [28]:
import numpy as np

## Data types and attributes

In [29]:
# Numpy main datatype is ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [30]:
type(a1[0])

numpy.int32

In [31]:
a2=np.array([[1,2,3],[3.4,3,5.7]])
a3=np.array([[1,2.2,3.1],[3.4,3.1,5] ])
a3

array([[1. , 2.2, 3.1],
       [3.4, 3.1, 5. ]])

In [32]:
a2.shape
a1.ndim,a2.ndim,a3.ndim

(1, 2, 2)

In [33]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [34]:
a1.size,a2.size,a3.size

(3, 6, 6)

In [35]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [36]:
## create dataframe from a numpy array

In [37]:
import pandas as pd

In [38]:
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  3.4  3.0  5.7

## creating numpy arrays

In [39]:
sample_ar=np.array([1,2,3])
sample_ar

array([1, 2, 3])

In [40]:
sample_ar.dtype

dtype('int32')

In [47]:
ones=np.ones((5,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])