# NumPy library

In [1]:
import numpy as np

## range function
when we want to use numbers in particular range in python

Syntax


       range(start, stop, step)

In [2]:
list(range(0,5,2))

[0, 2, 4]

In [3]:
list1=[1,3,5,7,9]
list2=[2,4,6,8,10]

new_list=[]

for i in range(0,len(list1)):
    new_list.append(list1[i]*list2[i])
    
new_list
    

[2, 12, 30, 56, 90]

In [4]:
# using numpy to multiply two lists
x=np.array(list1)
y=np.array(list2)
z=x*y
z

array([ 2, 12, 30, 56, 90])

## the Array() function
is a data structure in NumPy library. it looks like a list or even a tuple


In [5]:
# single format of fixced type
variable=[5.8,9,7,5]
print(type(variable[0]))
print(type(variable[1]))

new_variable=np.array([5.8,4,6,8],dtype='int')
new_variable


<class 'float'>
<class 'int'>


array([5, 4, 6, 8])

## the zeros() function
create a numpy array with the zeros() function

In [6]:
np.zeros((3,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## the ones() function
create a numpy array with the ones() function

In [7]:
np.ones((3,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## the full() function
it will fill the array of the size we want and th shape we want with the numbers
that we want

In [8]:
np.full(8,5)
np.full((2,3),6, dtype='float')

array([[6., 6., 6.],
       [6., 6., 6.]])

## the arange() function
this function can produce numpy arrays of the datatype that we want according
to our determined start and endpoints

syntax

arange(start,stop,step,dtype)

In [9]:
np.arange(5)
ex=np.arange(3,10,dtype='float')
ex

array([3., 4., 5., 6., 7., 8., 9.])

## the eye() function
this function allows to produce a unit(identity) matrix


In [10]:
np.eye(5,dtype='bool')
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## the linspace() function
this function help us to create a certain number of values between two values



In [11]:
np.linspace(10,30,30,dtype='int')

array([10, 10, 11, 12, 12, 13, 14, 14, 15, 16, 16, 17, 18, 18, 19, 20, 21,
       21, 22, 23, 23, 24, 25, 25, 26, 27, 27, 28, 29, 30])

## the random() function
this function help us to create a certain number of values between two values



In [12]:
np.random.rand(5,3)
np.random.randn(5,3)# random numbers according to normal distribution
np.random.normal(loc=10,scale=5,size=(4,2))
np.random.randint(0,10,(4,3))# random numbers in intgers only

array([[4, 6, 5],
       [9, 7, 9],
       [4, 0, 1],
       [3, 2, 6]])

## the reshape() function
this function used to shape the numpy array



In [13]:
reex= np.arange(1,16)
reex

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
reex.reshape((3,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
new_array=reex.reshape((1,15))
new_array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [16]:
reex.reshape((5,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

## the max() and argmax() function
max() this function help us to identify the the largest number of arrays

argmax() this function help us to identify the index of the largest number of the array



In [17]:
reex.max()

np.int64(15)

In [18]:
reex.argmax()

np.int64(14)

## the min() and argmin() function
min() this function help us to identify the the smallest number of arrays

argmin() this function help us to identify the index of the smallest number of the array



In [19]:
reex.min()

np.int64(1)

In [20]:
reex.argmin()

np.int64(0)

## the concatenate() function
this function used to concatenate two arrays together

In [21]:
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])

In [22]:
np.concatenate([array1,array2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
array3=np.arange(1,7).reshape((2,3))
array4=np.array([[3,6,9],[9,5,8]])

np.concatenate([array3,array4],axis=1)

array([[1, 2, 3, 3, 6, 9],
       [4, 5, 6, 9, 5, 8]])

## the split() function
this function used to split array into two arrays

In [24]:
array=np.array([1,2 ,3,4,50,64,2,6])

np.split(array,[3,5])

[array([1, 2, 3]), array([ 4, 50]), array([64,  2,  6])]

## the sort() function
this function used to sort the array

In [25]:
variable=np.array([3,5,6,4,2,8,7,9])
variable

array([3, 5, 6, 4, 2, 8, 7, 9])

In [26]:
variable.sort()
variable

array([2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.sort(variable,axis=0)

array([2, 3, 4, 5, 6, 7, 8, 9])

## indexing numpy arrays


In [28]:
array=np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
array[2]

np.int64(2)

In [30]:
array[-2]

np.int64(9)

## slicing one-dimensional numpy arrays

In [31]:
example=np.arange(10,20)
example

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [32]:
example[2:6]

array([12, 13, 14, 15])

In [33]:
example[3::2]

array([13, 15, 17, 19])

## opertaions in NumPy arrays

## operarions with comparison operators

In [34]:
array=np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
array>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [36]:
array[array<5]

array([1, 2, 3, 4])

In [37]:
condition=array<=4
condition
array[condition]

array([1, 2, 3, 4])

## operarions with arithmetic operators

In [38]:
array*array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [39]:
np.multiply(array,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

## statistical operations in NumPy

In [40]:
array.sum()

np.int64(55)

In [41]:
np.mean(array)

np.float64(5.5)

In [42]:
np.std(array)

np.float64(2.8722813232690143)

In [43]:
np.median(array)

np.float64(5.5)

## solving second-degree equations using numpy 

In [44]:
coefficient =np.array([[2,1],[-3,6]])

In [45]:
output=np.array([5,0])

In [46]:
np.linalg.solve(coefficient,output)

array([2., 1.])